### PR TITLE
Decreased the amount of allocations

### PR DESCRIPTION
**Pull request by renaudcerrato**
Your current implementation is allocating **A LOT** of useless objects which can be saved with some temporary member variables. I fixed all of them, along with some minor cleanup.

### CODE REVIEW

**Comment by apacha** [comment]
Cool stuff. I will take a look at it and merge it in the next few days. Thanks for your work.

**Comment by apacha** [comment]
It's hard to review this pull request, because you have opened it from a private repository, and I can not check out the branch, review it offline and the accept the pull-request and merge it. But since this repository is only a mirror of the main bitbucket repository, I will accept the pull request for now, while I review it.

**Comment by renaudcerrato** [comment]
Ah... The repository was public, but I recently deleted it. I thought the PR would handle that properly. Sorry for the mess. 

This was mainly about avoiding  allocations in sensor callbacks. There was also some minor cleanups, like misnamed/unused methods or classes. I could have splitted everything in multiple PR.

**Comment by apacha** [comment]
The pull request is still there and I have all your changes, but I wasn't able to check them out _before_ merging them. But it doesn't really matter now. Thanks for your work. I will add you to the list of contributors.

**Pull request merged**
